version: '2'
redis_password: &redis_password FILLYOURPASSWORDINHERE
services:
  redis-sentinel:
    image: brentclark/redis-sentinel
    environment:
      REDIS_PASSWORD: *redis_password
    stdin_open: true
    tty: true
    restart: always
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.scheduler.affinity:container_label_ne: redis-sentinel=1
      io.rancher.container.start_once: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
  redis-server:
    image: brentclark/redis-server
    environment:
      REDIS_PASSWORD: *redis_password
    stdin_open: true
    tty: true
    restart: always
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.global: 'true'
  redislb:
    image: brentclark/redis-haproxy-lb
    environment:
      REDIS_PASSWORD: *redis_password
    stdin_open: true
    tty: true
    ports:
      - 6390:6378/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.global: 'true'
    depends_on:
      - redis-sentinel
      - redis-server
