version: '2'
services:
  redis-sentinel:
    start_on_create: true
    scale: 3
    retain_ip: true
    health_check:
      port: 26379
      interval: 2000
      strategy: recreate
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
  redis-server:
    start_on_create: true
    retain_ip: true
    scale: 3
    health_check:
      port: 6379
      interval: 2000
      strategy: recreate
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
  redislb:
    start_on_create: true
    scale: 3
    retain_ip: true
    health_check:
      port: 6378
      interval: 2000
      strategy: recreate
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000

